# Generated by Django 5.1.1 on 2024-09-04 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('num_positions', models.PositiveIntegerField()),
                ('level', models.CharField(max_length=100)),
                ('kra', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urgency', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
