# Generated by Django 5.1.1 on 2024-09-05 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
